#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

MODULEDIR ?= /usr/share/puppet/modules

install:
	install -d -m 0755 $(MODULEDIR)/dcagent
	cp -R dcagent/ $(MODULEDIR)/
