#
# Copyright (c) 2018-2019 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# Tox (http://tox.testrun.org/) is a tool for running tests
# in multiple virtualenvs. This configuration file will run the
# test suite on all supported python versions. To use it, "pip install tox"
# and then run "tox" from this directory.
[tox]
toxworkdir = /tmp/{env:USER}_puppet-modules
envlist = puppetlint
skipsdist = True

[testenv]
recreate = True

[testenv:puppetlint]
# Note: centos developer env requires ruby-devel
# Ubuntu developer env requires ruby-dev
deps =
allowlist_externals =
    gem
    bash
setenv =
    GEM_HOME = {envdir}
    GEM_PATH = {envdir}
# skip_tests: common lint options for all distros (including trixie)
skip_tests = \
    --fail-on-warnings \
    --no-autoloader_layout-check \
    --no-documentation-check \
    --no-variable_scope-check
# skip_tests_bullseye: additional options only needed for bullseye
skip_tests_bullseye = \
    --fail-on-warnings \
    --no-autoloader_layout-check \
    --no-documentation-check
commands =
    gem install --no-document json puppet-lint:2.3.6
    bash -c "find {toxinidir} -path '*/debian/trixie/*.pp' -print0 \
                | xargs -r -0 puppet-lint {[testenv:puppetlint]skip_tests}"
    bash -c "find {toxinidir} -path '*/debian/bullseye/*.pp' -print0 \
                | xargs -r -0 puppet-lint {[testenv:puppetlint]skip_tests_bullseye}"
    bash -c "find {toxinidir} -path '*/debian/all/*.pp' -print0 \
                | xargs -r -0 puppet-lint {[testenv:puppetlint]skip_tests}"

