---
- project:
    templates:
      - stx-bandit-jobs
    check:
      jobs:
        - stx-puppet-linters
        - stx-puppet-tox-pep8
        - stx-puppet-tox-pylint
        - puppet-manifests-tox-py39
    gate:
      jobs:
        - stx-puppet-linters
        - stx-puppet-tox-pep8
        - stx-puppet-tox-pylint
        - puppet-manifests-tox-py39
    post:
      jobs:
        - stx-stx-puppet-upload-git-mirror

- job:
    name: stx-puppet-linters
    parent: openstack-tox-linters
    description: |
      Run linters for stx-puppet
    pre-run: playbooks/tox-puppet-lint/pre.yaml

- job:
    name: stx-puppet-tox-pep8
    parent: openstack-tox-pep8
    nodeset: debian-bullseye
    description: |
      Run pep8 checks for stx-puppet
    vars:
      python_version: 3.9

- job:
    name: stx-puppet-tox-pylint
    parent: openstack-tox-pylint
    nodeset: debian-bullseye
    description: |
      Run pylint checks for stx-puppet
    vars:
      python_version: 3.9

- job:
    name: puppet-manifests-tox-py39
    parent: openstack-tox-py39
    description: |
      Run py39 test for puppet-manifests
    nodeset: debian-bullseye
    files:
      - puppet-manifests/*
    vars:
      tox_envlist: py39
      python_version: 3.9
      tox_extra_args: -c puppet-manifests/tox.ini

- job:
    name: stx-stx-puppet-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/stx-puppet to
      github.com/starlingx/stx-puppet
    vars:
      git_mirror_repository: starlingx/stx-puppet
    secrets:
      - name: git_mirror_credentials
        secret: stx-stx-puppet-github-secret3
        pass-to-parent: true

- secret:
    name: stx-stx-puppet-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - h/0wgC8aYz7kvAWlULGKGxeod8dGaLux/4GoZDXIl05MLQaXNwBW1+faqRi8K8P1CFKHM
          eWn9my3GHoJGd7wobBnvw0d5VRVjkZI6DZQ+cPTxAR1w5u2KRxjTWU+PoIdTEH4bc0wiW
          qqL38y9VcaIdhCENQ95ydLiYp99A08IEI6Q6lcmlFge+l+qTXUWjG724dq2p8rJS81y2j
          ocr+CttFfza5/NiLkkBXKbjRNi2a+ylveK9sVLT88lPwRRUE7JSfCtqGlJTRk6neOD9dt
          bO9jWIofTky82E3ScuebVqTXG1aZQ3sAa6ov9dTDHRrHlklHmPFvTWkhKgFSiRriCs3z6
          SakJhlsz0kgWNLldwOaxWKdLFrIsW+SEAFp80eMAK/tKQ4I2xK8ted1+96uAYtr/Yieup
          juga2LQ5wAmen5soJDPVLy+vj1H1+333LAicAXj30PAEaSDlmPs3ZAect61wgYavMRWMt
          OdcYypc12ugGs2VlSXjXxKvMcFVcFGxv42114WDSuu8ue/P0FEpvUPoJKVcrvXDUs5Qv3
          Vg5vtymyCDG3IBtPhflkBaItDMezAVTs/CBbM9qEuvSP6yw5N38z0sZx3LG3CD2cKkwAU
          DYyK6eBkep2hJRwcfslc3maLgeXGKuF4xIEKLUgU/KSgnCYcZgtu/Rp9XHaWnA=
        - W8xfUwAqnC7mLMCcS2n4hw2/kWiS46USWpPMcVzYlUcMbzJWMKyx4N3mTyd7K5DHJ+iz9
          HxTjk5xAu/wauHWQcHh+IyYbQyhs3XGGlzpzmQRfmI2gFPy1co2G07w2GndkPO8/lhMSU
          GQOPClNGJswBPL9occ7sF+uZxB0R7/knFXONlOZIvVVJy4Bs3+PLb7+TV4pBGLMWXBQNY
          8GUtKx6Ap2fwHPe5XlVHEA77qBJg2xoc6M3CULfcmg9HNHKStW6UOYnjFgGRFBjX2l6us
          ucSy4ujCRAo4/R+tj+ChJ4QHJ34m7ZSW7nlCQJzPvN5rryMlBQAhZ0GBFflt7EgT9Tk8H
          llnIccO6DVS+Ag7dcQX+dxpWkmhW2/g+WenHKF5ODePatPW9nnDKpTcU1Ju0p28/CU1sn
          CuDbIHfzMn5ZPAhyddyV3L0nf0grVcIJUw3AFO0vw75K5KNwfbERmOXBY/2z7A7Q74lgv
          01UBdhcHhVxVQYbgVrj+7W40HWSUNItwVUvcAnfKwF6qW4BeVEeST+AoSRd8HDf8hyVke
          bayBB44H5OA8Xgl83PDIYoxTE5zOGnLs3chkibPyrPgkcGXjkb0rh0HfQHqqwlC6VmiHy
          RZwSc8T68yj6fBPfCNR426djkf9LQguZuitKdu8wVHUKDaF0m0LUd/ZGfRiE2g=
        - sXzvc+C2cW+OIPpH0w8fvTCqEFgqdHMSecLF0Lg4uNJXOtAC5pr+tJsvoIcw+aEZPONJt
          7FSH4uSoF3u8IepHqH05eALIBJYvVYtja4RyE4OHQWhcPPoGviyOTCVsEdPqDq8hpsvVY
          cNv0L0EEkCQM2YHcKKxjsBM+hYnTx85LSmA1/J5JSOPyqKJYCodN2/nahLzGTqXmU3gzO
          BRlwJzAJhaVGI0cnTOQEWRnZX78tpR0e5/Ea4IRa1oAqt1YHtxT5QSKEBwmZDdhy/wfSF
          YBeicYA/0GaX1MAFPa55IPu7mdz73uqxuIDWkLkT9hYw7zqyrEVwLGfC4z20AHZdL4tln
          00p4hQUV7XYCiPvkRH7CFIPNWuAbvU0id5ptpOQz/Dn9wOAOAmpqlz6WEZuqX6YvjBnYH
          QimZqDnWWtuoDt7nCN4sUP+4n5Kyq7DJmqvmmlOcOn9vUUZ0qOIemhZ7St2Mdk4YGvfJm
          tgTQIZYEelOGb6Ifb7FB6g7e7pwGD8RNyLnln/FGNE43H0fiwYqpzrY5x0fXXADSDTW6B
          WlUMrV7lDyc+NyA6w8AYF2VcyNPqGH09n2SmME+/xlYdSe6fbVY7nsy3cviJyVkEb7A1S
          cN0CqLpiR1GHMyyg8TWFOp0hoO2KMNuvf+gLq98X0cQqSyaji+4yM3m6fcIv1g=
        - KB0FFdr/P+x0dZcqv3EQcvj9Z3gJl0HBLLkgYJMdxO1+oZ7wEQeaf0MxdlxYZXk/HzByI
          6FqYDbShrhg4aW8uUpRY29yfh1Kvzpt/8KJ+kj3UldLA/VV8a+tslV0xS6TG3dRVngnGv
          1J8u+Rxup4MLmYkmiULxW5CIE4gwaRsBhdLvV3DxAOsccVVNav3BOgHJ2EwCR2h1ooTYY
          WSp03Qdmqi8ksO8hawxfvk5uEI0bSpLwTETzXnMXl2apZ4z5Imkg3iXNvD1L1mUmiQGB1
          4C0B9q/ilx+plVh98zksFsi1LsJHZ7VlSRBAcwTFcQhCrXBqtxJJMsUYGm6EIvPKyCcrI
          y/0QaInEoUufSfSQDXhbG+SO2TZYSh+a7q/PBrPz8t4Z9XymxSF8c//GAFFn45NM0FC86
          mUcLd0Z4zBKl4iwiNKcHwc43SX8/4oRXzBQPmvjhU7U83tvuzzohrPrCmYFndEyW7Ng55
          uM0FCDN3LLG96uCiCNGqf/YFfVfj/i6TpSTR1ps0NSXrhCft5XwMzv+dFyYvnrmwyacgJ
          swqIvdTbptiEhM4btN+n728FK9gWAmhSkHJwTJJNdJhJ+X85qd183QFsFULH+XWbV0HF5
          5S6BWIIXzCpM4OiLTbxFYxMm5QAx3fq7hRy6jABsqpBQVxCMADlAKv85xnAp2E=
        - ZTI27yU3+N0jmioz9UMnlfaJSA+HJD0CvoyjnFn2MjcIpyq1rxUdkwr98ZFdc0ITMuwKj
          8lQv1lpi1vKRNYf8KwYxCMdrO7aZnPAPIHE3SPOvzC4JDdjhl9NYkCHyJnG7rT2yl1ZPL
          r2czZYnu3F7K2yo2joNBjSEWhiNRpX49V01zfDn5AeywJtL9ux0/GOiotBSicHb6ec005
          B+OdYTLyx5hMoYPFkURUDMNTlHyjm/OTz/wzf0ywtg1AM0w7c/8R/6wpwyzG8SrDcBDO/
          v3L7QoH2ajq/ogzCXe83DMA9Vh3T59WdCcmFtMB69WqBzJSLMJWA6y12zMohnlXYG3QPj
          e4xfB/ksnWpLNnC2cJZEk/kSN74qJriSczZ9ee6cyKtIIl/q1dQcS8CjPBbI9aEmH6HZJ
          C5NwwoY45zCFS0yqzSCsscysW7qUasmDJVzgL8CRP2xpVoDTxPHCJGYfxWoRH/I6a3Yxj
          kVX/rQQ0cVSZi00Jd86I/cB5wyNZKZ6+n/bu8MyCbWgkk/5wQzUACpUc+o99wd3YjkkPI
          7CjT5nw/tPXv458prFvmixqbB59yZdaKT7VPaJeh2Ng8L5Z0h4wei2yVHrm+CNHbdXQRo
          h7PELsGIMDvly5UUbMO+OqJMIswwIHO2gOs2kTIP5GSW/mTl9Nx7TOjMn71x0w=
        - PpN5J4ydlu9FWbjB+ws1ZEQ5zEz8fVLscumqyFE7/QCEP4FN4HbXmnh0qKWGrSblUPPCU
          xMFYLfWe7C668dnNdVccCeMnCDjen/aUL67jdUoLmoqnoME+8DuLdSNOTQn1KpQwCMGC2
          JY1wttMei03zSZVJxPFiZVJqYv3liah6fbcDxqKK+BEcdzE1qvhqcVdUIdJ0m6Lm6sNyy
          zXIvFTBSRg7R+NO5sdLSv/+qKldNA7wpq/2pQsZM5dk4MDTCg8lGPv3KhpogLK/HQHEwy
          7l7KYqfsmzOXSr04r+iSXFZRkh0bBGoMPlxZeoxJaEGdShzFeHKTRK9BuFJAxDRzkyF92
          qB2ZLKaLHYfhjiiTJDUcSDqWjiWWziqLZPufe1FWXDa/d1gpYaj+2SqSMciR7x2JBebca
          DXJpFOAZqjDZmy0sXn0p19fp/9tE8+yOTqsfWG9Imw5yGKqsSIGB8T0ocNbqHAnjqzlaz
          lsi80QY+UhRxT73Zx5fmd1WJR5tBBueUVqiGcPMRPmEspmcQvgkjTq0/b8Fp8YP4gJi31
          nVKqJs6zVPt5LRL5jxlwsfVAvJeXAHB5Ihi0WXNnfUM5ClLXk/BxB+l2XhvYMwPAZK6qG
          8IQRDghVVVzE53iepeBhfK8AdGML4kPDOlN6HOlHVKS+v2f7A0IzNgafrVatnw=
        - qI/jYJvsB8PZWSKpSkb7+57Acktf0WNe+q0aVT90pU21W+qOkPXbkFBWQquky6iM1bppP
          mfBsW12NnqjeDCQXa7JokHlzS80o4zld6+K4aEL4/O97tV6efiBD5hgsgJO5NC4FCHuWt
          02BsMFN8rcKR3oouuTLceCEs4Lvbed9L1sHeyC/jhnXVxfHeHUhovjoJN5iSuk973eT34
          kVsxJMvVQBlufRk/tNL4FTDlRVry+TFZGkpOGqQhRaRM+0iDIGZL6zfT2V2YfKHQGPBBV
          2DeQHD1ctYl/HTAWjwCsiH4WFG6QYhdq0k4XAuGa6vWLKZsuV7JIdZi9Ce3qdKjWdwIqj
          YJOHU3qDjzvdihlDkKUa0XcBsIY0iyOitPwvb0s4fY3W4sVxQ5vU21jMY/q9CzEZxuY1T
          RpF1lT4fdJ9JgPZ5itUDj2IEHBKCLJvGReTgl9Hd6YHcvowha1lY4y4EDMsv4YvjdrfK0
          ZHeDtmjHdce94Lb3oyOVrxs60pumxZSffEiGEyc0KQbZTu49Mo5pfQ4pH1decqgwlXKQr
          ImuzJRD0d+uObqzxCdFq7JTHrZC97dRzr2EgIRmE4ufFTtpW1WQbDH5ta3xOuT8HwUZvj
          n1iUQml8sC4Ebz2naBHWvZaMWfGWVB6Xo6FqF779Ng5gyc+d7avcEz3iHQ2LUA=
