#
# Copyright (c) 2023 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

MODULEDIR ?= /usr/share/puppet/usm
MODULE_NAME ?= usm

install:
	install -d -m 0755 $(MODULEDIR)/$(MODULE_NAME)
	cp -R $(MODULE_NAME)/ $(MODULEDIR)/
